# Location and name of the sample_sheet:
sample_sheet: sample_sheet.yaml
out: out

######################################
### Software parameters            ###
######################################

Trimmomatic:
    # For the Nextera PE lib prep adapters
    adapter_removal_config: ILLUMINACLIP:files/trimmomatic_0.36_adapters_lists/NexteraPE-PE.fa:2:30:10:8:true
    # ! test settings for best "relaxed" mode
    # Default is 5 nucleotides window size, minimum average Phred score of 20
    quality_trimming_config: SLIDINGWINDOW:4:20
    # Default is Remove anything smaller than 50 nucleotides
    minimum_length_config: MINLEN:40

bwa:
    ref_genome: '/mnt/db/Myco_lofreq_files/refgenome_H37Rv3.fasta'

vcf_annotator: 
    annotated_genome: '/mnt/db/Myco_lofreq_files/Genebank/GCF_000195955.2_ASM19595v2_genomic.gbff'


######################################
### Technical parameters           ###
######################################

threads:
    trimmomatic: 4
    bwa: 12
    picard: 4
    lofreq: 12
    annotated_vcf: 1
